global:
  security:
    allowInsecureImages: false

cluster:
  enabled: true
  replicas: 2
  jgroups:
    port: 7800
    kube_ping:
      version: "2.0.1.Final"
      url: "https://nexus.xwiki.org/nexus/service/local/repositories/central/content/org/jgroups/kubernetes/jgroups-kubernetes/${KUBEPING_VERSION}/jgroups-kubernetes-${KUBEPING_VERSION}.jar"

image:
  name: xwiki
  tag: 17.10.2-postgres-tomcat

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "4Gi"

javaOpts:
  - "-server -Xms1536m -Xmx2048m -Dfile.encoding=utf-8 -Djava.awt.headless=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED -XshowSettings:all -Duser.timezone=Asia/Ho_Chi_Minh"

extraEnvVars:
  - name: TZ
    value: Asia/Ho_Chi_Minh

solr:
  # If set to false mount an internal Solr instance
  enabled: true
  # image:
  #   tag: latest
  downloadCores:
    enabled: true
  persistence:
    size: "5Gi"
  probes:
    customReadiness:
      httpGet:
        path: "/solr/admin/info/system"
        port: 8983
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 15
      failureThreshold: 6
      successThreshold: 1
    customStartup:
      httpGet:
        path: "/solr/admin/info/system"
        port: 8983
      initialDelaySeconds: 40
      periodSeconds: 10
      timeoutSeconds: 15
      failureThreshold: 15
      successThreshold: 1

route:
  enabled: true
  host: "xwiki.unit.local"
  path: "/"
  targetPort: http
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: None

workloadStateful: false

mysql:
  enabled: false

externalDB:
  type: "postgresql"

persistence:
  enabled: true
  existingClaim: "pvc-xwiki-cluster-data"
  mountPath: /usr/local/xwiki/data

customConfigs:
  xwiki.cfg:
    xwiki.authentication.authclass: org.xwiki.contrib.oidc.auth.OIDCAuthServiceImpl
    xwiki.monitor: "0"
    xwiki.backlinks: "0"
    xwiki.authentication.group.allgroupimplicit: "1"
    xwiki.store.cache.capacity: "1000"
    xwiki.store.versioning: "1"
    xwiki.recyclebin: "1"
    xwiki.home: https://xwiki.unit.local/
    xwiki.url.protocol: HTTPS
    xwiki.store.recyclebin.adminWaitDays: "3"
    xwiki.store.recyclebin.waitDays: "3"
    xwiki.stats: "0"
    xwiki.stats.default: "0"
    xwiki.rendering.defaultCacheDuration: "3600"
  xwiki.properties:
    ### OpenID Connect Authenticator ###
    oidc.endpoint.authorization: https://iam.unit.vn/auth/realms/unit-corp/protocol/openid-connect/auth
    oidc.endpoint.token: https://iam.unit.vn/auth/realms/unit-corp/protocol/openid-connect/token
    oidc.endpoint.userinfo: https://iam.unit.vn/auth/realms/unit-corp/protocol/openid-connect/userinfo
    oidc.scope: openid,email,offline_access,profile
    oidc.endpoint.userinfo.method: GET
    oidc.user.nameFormater: ${oidc.user.preferredUsername._clean._lowerCase}
    oidc.user.subjectFormater: ${oidc.user.subject}
    oidc.idtokenclaims: true
    oidc.userinfoclaims: xwiki_user_accessibility,xwiki_user_company,xwiki_user_displayHiddenDocuments,xwiki_user_editor,xwiki_user_usertype
    oidc.userinforefreshrate: "600000"
    oidc.clientid: xen
    oidc.secret: gMA2POyY6rzdUiCVebQmvrYDTbLQVhOn
    oidc.endpoint.token.auth_method: client_secret_basic
    oidc.defaultClientConfiguration: default
    oidc.clientConfigurationCookie: oidcProvider
    oidc.afterLogoutURL: /xwiki/bin/view/Main/
    oidc.enableUser: true
    oidc.skipped: false
    ### Rendering Cache ###
    core.renderingcache.enabled: true
    core.renderingcache.documents: 'wiki:Space\.Page'
    core.renderingcache.duration: "300"
    core.renderingcache.size: "100"
    ### MAIL Configure ###
    mail.sender.host: mail.unit.vn
    mail.sender.port: "587"
    mail.sender.username: sysadmin@unit.vn
    mail.sender.password: bk9NtjE$C@nFECPi
    mail.sender.from: sysadmin@unit.vn
    mail.sender.database.discardSuccessStatuses: false
    mail.sender.properties: mail.smtp.starttls.enable = true
    mail.sender.sendWaitTime: "8000"
    csrf.enabled: false
    ### Store ###
    store.fsattach.cleanOnStartup: false
    store.blobStoreType: s3
    # store.blobMigrationStoreType: s3
    ### S3 Blob Store ###
    store.s3.bucketName: xwiki-cluster
    store.s3.accessKey: KMNOW45VXB00DFFUNR7V
    store.s3.secretKey: 5iW313qeWyijwH3DJQMG2yzGtXMuAZFv9uZlNkrW
    store.s3.endpoint: http://s3-seaweedsf.apps.vvt1.ocp4.unit.local/
    store.s3.pathStyleAccess: true
    # store.s3.keyPrefix: xwiki
    ### Clustering and events distribution
    observation.remote.enabled: true
    observation.remote.channels: kubeping
    observation.remote.kubeping.namespace: ${env:KUBERNETES_NAMESPACE}
    observation.remote.kubeping.labelSelector: app=xwiki
    observation.remote.kubeping.port: 8080
    observation.remote.kubeping.serviceName: xwiki-cluster
    ### SOLR Configure ###
    solr.type: remote
    solr.remote.baseURL: http://xwiki-cluster-solr:8983/solr
    solr.remote.configSet: xwiki
    # solr.remote.corePrefix: xwiki

customConfigsSecrets:
  xwiki.cfg:
    xwiki.superadminpassword:
      value: "Unit@032010"

logback:
  enabled: true
  extraConfiguration: |
    <logger name="org.xwiki" level="info"/>
    <logger name="com.xwiki" level="info"/>
    <logger name="org.xwiki.contrib.oidc" level="info"/>
    <logger name="com.xpn.xwiki.monitor" level="info"/>
    <logger name="org.xwiki.configuration.internal.DocumentsConfigurationSource" level="WARN" />

probes:
  startup:
    httpGet:
      enabled: false
      path: /rest
  liveness:
    initialDelaySeconds: 300
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 10
    successThreshold: 1
  readiness:
    httpGet:
      path: /rest
    initialDelaySeconds: 300
    timeoutSeconds: 10
    periodSeconds: 30
    failureThreshold: 10
    successThreshold: 1

customJdbc:
  enabled: true
  properties:
    connection.username: xwiki
    connection.password: Unit@032010
  postgresql:
    properties:
      connection.url: "jdbc:postgresql://edb-pg-dev.unit.local:5444/xwiki-cluster"
